version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${AWS_ID}.dkr.ecr.${REGION}.amazonaws.com
  build:
    commands:
      - docker build -t cicd-go .
      - docker tag cicd-go:latest ${IMAGE_URI}:latest
  post_build:
    commands:
      - docker push ${IMAGE_URI}:latest
      - echo "hoge" > test.txt
artifacts:
  files: test.txt