version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - REPOSITORY_URI=${IMAGE_URI}
  build:
    commands:
      - docker build -t ${IMAGE_URI}:latest .
  post_build:
    commands:
      - docker push ${IMAGE_URI}:latest
artifacts:
  files: output.json